### ISSUE TITLE
DLL in the release

### ISSUE THREAD

**Issue by Antoniofo** [FoxWorn3365/UCRNicknameExtension#1]
Hello,
The DLL provided in the release is compiled on the 4.8 .NET framework in debug.

**Comment by FoxWorn3365** [comment]
Yes, you should download the version of UCR v2 0.0 rev2 or greatest from our Discord server in order to get this plugin working

**Comment by Antoniofo** [comment]
oh it works fine its just when i tried to recompile it because it was in debug that i found about that
